# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
        AppBundle\Security\User\UserProvider:
            algorithm: bcrypt
        AppBundle\Security\User\SecurityUser:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        webservice:
              id: AppBundle\Security\User\UserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            http_basic: ~
            provider: webservice
            form_login:
                            login_path: login
                            check_path: login
            logout: true
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
      - { path: ^/add/city$, role: ROLE_USER }